# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fasterer-csv}
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mason"]
  s.date = %q{2010-06-21}
  s.description = %q{CSV parsing awesomeness}
  s.email = %q{mason@chipped.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "fasterer-csv.gemspec",
     "lib/fasterer_csv.rb",
     "pkg/fasterer-csv-0.0.1.gem",
     "pkg/fasterer-csv-0.0.10.gem",
     "pkg/fasterer-csv-0.0.11.gem",
     "pkg/fasterer-csv-0.0.12.gem",
     "pkg/fasterer-csv-0.0.14.gem",
     "pkg/fasterer-csv-0.0.2.gem",
     "pkg/fasterer-csv-0.0.3.gem",
     "pkg/fasterer-csv-0.0.4.gem",
     "pkg/fasterer-csv-0.0.5.gem",
     "pkg/fasterer-csv-0.0.6.gem",
     "pkg/fasterer-csv-0.0.7.gem",
     "pkg/fasterer-csv-0.0.8.gem",
     "pkg/fasterer-csv-0.0.9.gem",
     "pkg/fasterer-csv-1.0.0.gem",
     "pkg/fasterer-csv-1.1.0.gem",
     "pkg/fasterer-csv-1.2.0.gem",
     "spec/fasterer_csv_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/gnovos/fasterer-csv}
  s.post_install_message = %q{Kernel Panic!  System32 deleted!  Klaxons klaxoning!  Dogs and Cats living together!!!!  We're doooomed!  Everything is...
oh, no wait, it installed fine.  My bad.
}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Even fasterer than FasterCSV!}
  s.test_files = [
    "spec/fasterer_csv_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

